apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-service-deployment
  namespace: techniska-backend
  labels:
    app: result-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-service
  template:
    metadata:
      labels:
        app: result-service
    spec:
      containers:
        - name: result-service
          image: techniska-result-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: techniska-config
            - secretRef:
                name: techniska-secret 
                
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: techniska-backend
spec:
  type: ClusterIP
  selector:
    app: result-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080