apiVersion: v1
kind: ConfigMap
metadata:
  name: language-configs
  namespace: sandbox  # CRITICAL: Must match your deployment namespace
data:
  languages.json: |
    {
      "python": {
      "fileName": "solution",
      "extension": "py",
      "compileCommand": null,
      "executeCommand": "/usr/bin/python3 {file}",
      "memoryLimitMb": 128,
      "timeoutMs": 5000,
      "processes": 2
    },
      "java": {
      "fileName": "Main",
      "extension": "java",
      "compileCommand": "/opt/java/openjdk/bin/javac Main.java",
      "executeCommand": "/opt/java/openjdk/bin/java -Xms32m -Xmx128m -XX:MaxMetaspaceSize=128m Main",
      "memoryLimitMb": 512,
      "timeoutMs": 5000,
      "processes": 50
    },
      "cpp": {
      "fileName": "solution",
      "extension": "cpp",
      "compileCommand": "g++ -O3 -o solution solution.cpp",
      "executeCommand": "./solution",
      "memoryLimitMb": 128,
      "timeoutMs": 5000,
      "processes": 1
      }
    }