apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-service-deployment
  namespace: sandbox
  labels:
    app: worker-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-service
  template:
    metadata:
      labels:
        app: worker-service
    spec:
      containers:
        - name: worker-service
          image: worker-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            # 🔽 add RabbitMQ envs here
            - name: SPRING_RABBITMQ_HOST
              value: "host.docker.internal" # or better: host's private IP
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "guest"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "guest"
---
apiVersion: v1
kind: Service
metadata:
  name: worker-service-service
  namespace: sandbox
spec:
  type: ClusterIP
  selector:
    app: worker-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
